channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - biopython=1.84
  - ipywidgets=8.1.5
  - logomaker=0.8
  - matplotlib=3.8.4
  - matplotlib-venn=1.0.0
  - natsort=8.4.0
  - notebook=7.2.2
  - numpy=1.21.2
  - pandas=1.4.2
  - polars=0.20.31
  - pyarrow=17.0.0
  - scikit-learn=1.0.2
  - scipy=1.7.3
  - seaborn=0.13.2
  - tqdm=4.66.5
  - umap-learn=0.5.5
  - xlsx2csv=0.8.3
