channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9.20
  - numba=0.56.4
  - numpy=1.21.2
  - pandas=1.4.2
  - pyarrow=17.0.0
  - scikit-learn=1.0.2
  - scipy=1.7.3
  - tqdm=4.66.5
  - umap-learn=0.5.5
