channels:
  - conda-forge
  - defaults
dependencies:
  - pip=24.3.1
  - python=3.8.10
  - pip:
      - absl-py==1.0.0
      - accelerate==0.24.1
      - adapters==0.2.0
      - aiohttp==3.8.3
      - aiosignal==1.3.1
      - anyio==3.5.0
      - appdirs==1.4.4
      - argon2-cffi==21.3.0
      - argon2-cffi-bindings==21.2.0
      - astor==0.8.1
      - asttokens==2.0.5
      - astunparse==1.6.3
      - async-timeout==4.0.2
      - attrs==21.4.0
      - babel==2.9.1
      - backcall==0.2.0
      - beautifulsoup4==4.10.0
      - biopython==1.80
      - bleach==4.1.0
      - blis==0.7.9
      - boto3==1.26.16
      - botocore==1.29.16
      - bpemb==0.3.4
      - brotli==1.0.9
      - cachetools==5.0.0
      - catalogue==2.0.8
      - certifi==2021.10.8
      - cffi==1.15.0
      - chainer==7.8.1
      - charset-normalizer==2.0.12
      - click==8.1.3
      - cloudpickle==2.2.0
      - compress-json==1.1.1
      - confection==0.0.4
      - conllu==4.5.2
      - cycler==0.11.0
      - cymem==2.0.7
      - cython==0.29.28
      - datasets==2.19.1
      - debugpy==1.6.0
      - decorator==5.1.1
      - defusedxml==0.7.1
      - deprecated==1.2.13
      - dill==0.3.6
      - distiller==0.1.2
      - docker-pycreds==0.4.0
      - emojis==0.7.0
      - entrypoints==0.4
      - enum34==1.1.10
      - evaluate==0.4.2
      - executing==0.8.3
      - fastrlock==0.8
      - filelock==3.6.0
      - flair==0.11.3
      - flatbuffers==2.0
      - fonttools==4.31.2
      - frozenlist==1.3.3
      - fsspec==2024.3.1
      - ftfy==6.1.1
      - future==0.18.2
      - gast==0.5.3
      - gdown==4.4.0
      - gensim==4.2.0
      - gitdb==4.0.10
      - gitpython==3.1.31
      - google-auth==2.6.2
      - google-auth-oauthlib==0.4.6
      - google-pasta==0.2.0
      - grpcio==1.44.0
      - h5py==3.6.0
      - huggingface==0.0.1
      - huggingface-hub==0.22.2
      - hyperopt==0.2.7
      - idna==3.3
      - imageio==2.16.1
      - importlib-metadata==3.10.1
      - importlib-resources==5.6.0
      - inflate64==0.3.1
      - ipykernel==6.10.0
      - ipython==8.2.0
      - ipython-genutils==0.2.0
      - ipywidgets==7.7.0
      - janome==0.4.2
      - jedi==0.18.1
      - jinja2==3.1.1
      - jmespath==1.0.1
      - joblib==1.1.0
      - json5==0.9.6
      - jsonschema==4.4.0
      - jupyter==1.0.0
      - jupyter-client==7.2.0
      - jupyter-console==6.4.3
      - jupyter-core==4.9.2
      - jupyter-server==1.16.0
      - jupyterlab==3.3.2
      - jupyterlab-pygments==0.1.2
      - jupyterlab-server==2.12.0
      - jupyterlab-widgets==1.1.0
      - keras==2.8.0
      - keras-preprocessing==1.1.2
      - kiwisolver==1.4.2
      - konoha==4.6.5
      - langcodes==3.3.0
      - langdetect==1.0.9
      - libclang==13.0.0
      - lime==0.2.0.1
      - lmdb==1.3.0
      - loralib==0.1.1
      - lxml==4.9.1
      - markdown==3.3.4
      - markupsafe==2.1.1
      - matplotlib==3.5.1
      - matplotlib-inline==0.1.3
      - mdb-parser==0.0.3
      - mistune==0.8.4
      - more-itertools==9.0.0
      - mpld3==0.3
      - mpmath==1.3.0
      - multidict==6.0.2
      - multiprocess==0.70.14
      - multivolumefile==0.2.3
      - murmurhash==1.0.9
      - mxnet-cu112==1.9.0
      - nbclassic==0.3.7
      - nbclient==0.5.13
      - nbconvert==6.4.5
      - nbformat==5.2.0
      - nest-asyncio==1.5.4
      - networkx==2.7.1
      - nltk==3.8.1
      - notebook==6.4.10
      - notebook-shim==0.1.0
      - numpy==1.22.3
      - nvidia-cublas-cu12==12.1.3.1
      - nvidia-cuda-cupti-cu12==12.1.105
      - nvidia-cuda-nvrtc-cu12==12.1.105
      - nvidia-cuda-runtime-cu12==12.1.105
      - nvidia-cudnn-cu12==8.9.2.26
      - nvidia-cufft-cu12==11.0.2.54
      - nvidia-curand-cu12==10.3.2.106
      - nvidia-cusolver-cu12==11.4.5.107
      - nvidia-cusparse-cu12==12.1.0.106
      - nvidia-nccl-cu12==2.18.1
      - nvidia-nvjitlink-cu12==12.3.101
      - nvidia-nvtx-cu12==12.1.105
      - oauthlib==3.2.0
      - onnx==1.11.0
      - onnxruntime-gpu==1.11.0
      - opt-einsum==3.3.0
      - overrides==3.1.0
      - packaging==21.3
      - paddlepaddle-gpu==2.2.2
      - pandas==1.4.1
      - pandocfilters==1.5.0
      - parso==0.8.3
      - pathtools==0.1.2
      - pathy==0.10.1
      - peft==0.6.2
      - pexpect==4.8.0
      - pickleshare==0.7.5
      - pillow==9.0.1
      - plotly==5.15.0
      - pptree==3.1
      - preshed==3.0.8
      - prometheus-client==0.13.1
      - prompt-toolkit==3.0.28
      - protobuf==3.19.4
      - psutil==5.9.0
      - ptyprocess==0.7.0
      - pure-eval==0.2.2
      - py4j==0.10.9.7
      - py7zr==0.20.5
      - pyarrow==16.0.0
      - pyarrow-hotfix==0.6
      - pyasn1==0.4.8
      - pyasn1-modules==0.2.8
      - pybcj==1.0.1
      - pycparser==2.21
      - pycryptodomex==3.18.0
      - pydantic==1.10.7
      - pygments==2.11.2
      - pyparsing==3.0.7
      - pyppmd==1.0.0
      - pyrsistent==0.18.1
      - pysocks==1.7.1
      - python-dateutil==2.8.2
      - graphviz==0.8.4
      - pytorch-pretrained-bert==0.6.2
      - pytorch-transformers==1.2.0
      - pytz==2022.1
      - pywavelets==1.3.0
      - pyyaml==6.0
      - pyzmq==22.3.0
      - pyzstd==0.15.7
      - qtconsole==5.3.0
      - qtpy==2.0.1
      - regex==2022.10.31
      - requests==2.27.1
      - requests-oauthlib==1.3.1
      - responses==0.18.0
      - rsa==4.8
      - s3transfer==0.6.0
      - sacremoses==0.0.53
      - safetensors==0.4.1
      - scikit-image==0.19.2
      - scikit-learn==1.0.2
      - scipy==1.8.0
      - seaborn==0.12.1
      - segtok==1.5.11
      - send2trash==1.8.0
      - sentencepiece==0.1.95
      - sentry-sdk==1.24.0
      - setproctitle==1.3.2
      - six==1.16.0
      - smart-open==6.2.0
      - smmap==5.0.0
      - sniffio==1.2.0
      - soupsieve==2.3.1
      - spacy==3.5.3
      - spacy-legacy==3.0.12
      - spacy-loggers==1.0.4
      - sqlitedict==2.0.0
      - srsly==2.4.6
      - stack-data==0.2.0
      - sympy==1.12
      - tabulate==0.9.0
      - tape-proteins==0.5
      - tenacity==8.2.2
      - tensorboard==2.8.0
      - tensorboard-data-server==0.6.1
      - tensorboard-plugin-wit==1.8.1
      - tensorboardx==2.5.1
      - tensorflow-gpu==2.8.0
      - tensorflow-io-gcs-filesystem==0.24.0
      - termcolor==1.1.0
      - terminado==0.13.3
      - testpath==0.6.0
      - texttable==1.6.7
      - tf-estimator-nightly==2.8.0.dev2021122109
      - thinc==8.1.10
      - threadpoolctl==3.1.0
      - tifffile==2022.3.25
      - tokenizers==0.15.2
      - torch==2.1.1
      - torchaudio==2.1.1
      - torchvision==0.16.1
      - tornado==6.1
      - tqdm==4.66.4
      - traitlets==5.1.1
      - transformers==4.39.3
      - triton==2.1.0
      - tweepy==4.13.0
      - typer==0.7.0
      - typing==3.7.4.3
      - typing-extensions==4.5.0
      - urllib3==1.26.16
      - wandb==0.15.3
      - wasabi==1.1.1
      - wcwidth==0.2.5
      - webencodings==0.5.1
      - websocket-client==1.3.2
      - werkzeug==2.1.0
      - wget==3.2
      - widgetsnbextension==3.6.0
      - wikipedia-api==0.5.4
      - wrapt==1.14.0
      - xmltodict==0.13.0
      - xxhash==3.1.0
      - yarl==1.8.1
      - zipp==3.7.0
