channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9.20
  - biopython=1.84
  - ipympl=0.9.4
  - ipywidgets=8.1.3
  - logomaker=0.8
  - matplotlib=3.9.1
  - matplotlib-venn=1.0.0
  - natsort=8.4.0
  - notebook=7.2.1
  - numpy=1.24.4
  - pandas=1.5.3
  - polars=0.20.31
  - pyarrow=17.0.0
  - scikit-learn=1.5.1
  - scipy=1.13.1
  - seaborn=0.13.2
  - tqdm=4.66.4
  - umap-learn=0.5.6
  - xlsx2csv=0.8.3
